FROM node:18-alpine

# set working directory
WORKDIR /app

# copy dependency files
COPY package*.json ./

# install dependencies
RUN npm install --production

# copy source code
COPY . .

# expose port (sesuaikan dengan app kamu)
EXPOSE 8080

# start app
CMD ["npm", "start"]
