name: Build and Deploy to VPS 1GB

on:
  push:
    branches:
      - main # Jalankan otomatisasi setiap push ke branch main
    paths:
      - 'backend/**'
      - 'ml_recommender/**'
      - 'docker-compose.yml' # Ikut dipantau jika Anda mengubah port/env kontainer di VPS

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository }}/backend
  IMAGE_ML: ghcr.io/${{ github.repository }}/ml_recommender

jobs:
  # --- JOB 1: Build Image di Server GitHub ---
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push Backend Node.js
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:latest

      # Build & Push ML Python FastAPI
      - name: Build and Push ML Recommender
        uses: docker/build-push-action@v5
        with:
          context: ./ml_recommender
          push: true
          tags: ${{ env.IMAGE_ML }}:latest

  # --- JOB 2: Deploy Instan ke VPS ---
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # --- Solusi Timeout: Perpanjang napas koneksi SSH ---
          command_timeout: 20m
          timeout: 30m
          script: |
            cd /home/ubuntu
            
            # 1. Login Docker di VPS ke GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 2. Matikan container lama untuk mengosongkan RAM total di VPS sebelum ekstraksi dimulai
            docker compose down
            
            # 3. Bersihkan sisa cache gantung agar ruang penyimpanan lega
            docker system prune -f
            
            # 4. Jalankan Pull image secara bergantian (sequential) agar RAM tidak tercekik
            docker compose pull database
            docker compose pull backend
            docker compose pull ml_recommender
            
            # 5. Nyalakan kembali semua layanan secara berurutan
            docker compose up -d database
            docker compose up -d ml_recommender
            docker compose up -d backend
